### PR TITLE
fix deprecated pry syntax

### PR DESCRIPTION
**Pull request by 9edang**
fix deprecated pry syntax

### CODE REVIEW

**Comment by smakani** [comment]
It would be good to have this merged!

**Comment by christophejunier** [comment]
Could be fine to merge this one, this will remove `setting prompt with help of `Pry.config.prompt = [proc {}, proc {}]` is deprecated. Use Pry::Prompt API instead`

**Comment by agustin** [comment]
Hi @ascendbruce thanks for the gem! just wondering if is there something missing for this PR to be merged?

**Comment by ngelx** [comment]
This is much needed ... in the mean time ...

`gem 'awesome_rails_console', git: 'https://github.com/9edang/awesome_rails_console.git', branch: 'fix-deprecated-pry'`

**Comment by ascendbruce** [comment]
Hi @9edang, thank you for the PR, and sorry for the late response.

I've made a change based on your PR but add a little more backward compatibility. In particular, here is the change: https://github.com/ascendbruce/awesome_rails_console/commit/67e05e4d1eb89d7b2d6fce1cab0e41c314388a0f

I've also released a new version to rubygem as version `0.4.5`. Please give it a try :)

FYI @smakani @agustin @ngelx

**Pull request closed without merging**
